---
- name: Verify
  hosts: molecule
  gather_facts: true
  vars:
    tlp_service_manage: false

  tasks:
    - name: Load OS-specific vars
      ansible.builtin.include_vars: "../../vars/{{ ansible_facts.distribution | lower }}.yml"

    - name: Include Fedora
      ansible.builtin.include_tasks: tasks/verify-fedora.yml
      when:
        - ansible_facts.distribution == 'Fedora'
